name: assignment3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start logging
        run: |
          echo "Start time: $(date --iso-8601=minutes)" > log.txt
          echo "Submitter: $(git log -1 --pretty=format:'%an')" >> log.txt

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag my-image:latest && echo "Image successfully built" >> log.txt || echo "Image not able to be built" >> log.txt

      - name: Docker save
        run: docker save -o docker-image.tar my-image:latest

      - name: Archive Docker image and log file
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            docker-image.tar
            log.txt

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Docker image and log file
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Docker load
        run: |
          docker load -i docker-image.tar

      - name: Run the service in a Docker container
        run: |
          docker run -p 8000:8000 -d --name my-container my-image:latest && echo "Container up and running" >> log.txt || echo "Container failed to run" >> log.txt

      - name: Run Pytest
        run: |
          sleep 5 
          docker exec -t my-container pytest -v tests/assn3_tests.py > assn3_test_results.txt && echo "tests succeeded" >> log.txt || echo "tests failed" >> log.txt

      - name: Archive test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            assn3_test_results.txt
            log.txt

  query:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Download log file and pytest results
        uses: actions/download-artifact@v3
        with:
          name: test-artifacts

      - name: Docker load
        run: docker load -i docker-image.tar

      - name: Issue requests and save the results
        run: |
          docker run -p 8000:8000 -d --name my-container my-image:latest
          sleep 5
          while read -r food_item; do
              curl -L -X POST -H "Content-Type: application/json" http://localhost:8000/dishes -d '{"name": "'$food_item'"}'
              calories=$(curl http://localhost:8000/dishes/$food_item | jq -r '.cal')
              sodium=$(curl http://localhost:8000/dishes/$food_item | jq -r '.sodium')
              sugar=$(curl http://localhost:8000/dishes/$food_item | jq -r '.sugar')
              
              echo "$food_item contains $calories calories, $sodium mgs of sodium, and $sugar grams of sugar" >> response.txt
          done < query.txt

      - name: Archive query results and log file
        uses: actions/upload-artifact@v3
        with:
          name: query-artifacts
          path: |
            assn3_test_results.txt
            response.txt
            log.txt
